name: nudge
description: "A scheduler, reminder, and task board app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  package_info_plus: ^8.3.0
  wakelock_plus: ^1.3.2
  fluttertoast: ^8.2.12
  sqflite: ^2.4.2
  http: ^1.4.0
  uuid: ^4.5.1
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
 uses-material-design: true
 assets:
 - assets/images/logo.png
 fonts:
   - family: Inria Sans
     fonts:
       - asset: Assets/fonts/Inria_Sans/InriaSans-Regular.ttf
       - asset: Assets/fonts/Inria_Sans/InriaSans-Italic.ttf
         style: italic
       - asset: Assets/fonts/Inria_Sans/InriaSans-Light.ttf
         weight: 300
       - asset: Assets/fonts/Inria_Sans/InriaSans-LightItalic.ttf
         weight: 300
         style: italic
       - asset: Assets/fonts/Inria_Sans/InriaSans-Bold.ttf
         weight: 700
       - asset: Assets/fonts/Inria_Sans/InriaSans-BoldItalic.ttf
         weight: 700
         style: italic
   - family: Liter
     fonts:
       - asset: Assets/fonts/Liter/Liter-Regular.ttf
   - family: Roboto Flex
     fonts:
       - asset: Assets/fonts/Roboto_Flex/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf
   - family: Ubuntu
     fonts:
       - asset: Assets/fonts/Ubuntu/Ubuntu-Regular.ttf
       - asset: Assets/fonts/Ubuntu/Ubuntu-Italic.ttf
         style: italic
       - asset: Assets/fonts/Ubuntu/Ubuntu-Light.ttf
         weight: 300
       - asset: Assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
         weight: 300
         style: italic
       - asset: Assets/fonts/Ubuntu/Ubuntu-Medium.ttf
         weight: 500
       - asset: Assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
         weight: 500
         style: italic
       - asset: Assets/fonts/Ubuntu/Ubuntu-Bold.ttf
         weight: 700
       - asset: Assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
         weight: 700
         style: italic

flutter_launcher_icons:
 image_path: assets/images/logo.png
 android: "launcher_icon"
 min_sdk_android: 21
flutter_native_splash:
 image: assets/images/logo.png
 color: "#ffffff"